### ISSUE TITLE
Official address encoding base58check Vs bech32 vs base64

### ISSUE THREAD

**Issue by joyqvq** [MystenLabs/fastcrypto#1]
discuss after public testnet

**Comment by joyqvq** [comment]
after some attempts on using bech32 as Address and ObjectID encoding: https://github.com/MystenLabs/sui/pull/5643

there are few challenges that is hard to overcome due to `AccountAddress` defined in Move: 
1. All system object we use 0x5 instead of 0x000000000000000005 for representation, this makes it difficult for an objectID to be represented succinctly in bech32. 
2. In move contract, an address type uses AccountAddress in move as underlying, which is represented as hex, example https://github.com/MystenLabs/sui/blob/ea71d821684ccc1bae7034f2229c509c1b5318b8/crates/sui-framework/sources/governance/sui_system.move#L361
`assert!(tx_context::sender(ctx) == @0x0, 0);` this will cause a visual discrepancy on how sui uses an address vs what an address looks like onchain. 
3. the changes is quite invasive across the board, since we use AccountAddress in rust interchangeablely with SuiAddress and ObjectID (PR attempt: https://github.com/MystenLabs/sui/pull/5643)

Decision: to keep the address in hex instead of Bech32

**Comment by joyqvq** [comment]
Another question is whether we want to use 32 or 20 bytes for an hex address? this should be less invasive since there is a flag in Move to do this already. See all changes needed in https://github.com/MystenLabs/sui/pull/6700

**Comment by joyqvq** [comment]
cc @Jordan-Mysten to add considerations for address 32 bytes frontend 

also cc @kchalkias

**Comment by benr-ml** [comment]
@kchalkias, @joyqvq can we close this one? do you think we will want to change it in the future?

**Comment by joyqvq** [comment]
https://github.com/MystenLabs/sui/pull/8542 considers 32 bytes hex as final address format for mainnet.
