### ISSUE TITLE
[crypto] zeroize all secret cryptographic materials

### ISSUE THREAD

**Issue by punwai** [MystenLabs/fastcrypto#11]
### Description
Ensure that we zeroize on drop all secrets (private key and key pairs) for every signature scheme implemented.

- [x] BLS12-381
- [x] edDSA
- [x] ecDSA
- [x] BLS12-377

**Comment by kchalkias** [comment]
@joyqvq are we done with that issue?

**Comment by joyqvq** [comment]
need to confirm the last two. will do this week
