### ISSUE TITLE
[BLS12377] Add benchmarks for all functions and compare against 12381

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#137]

**Comment by jonas-lj** [comment]
@huitseeker mentioned that the implementation of BLS12377 is outdated. Should we update the implementation before we do the benchmarks, or should we just benchmark what we have?

**Comment by huitseeker** [comment]
You'll want to at least turn on the "asm" feature of ark_ff for benches.

**Comment by jonas-lj** [comment]
> You'll want to at least turn on the "asm" feature of ark_ff for benches.

Sure, I'll make sure to do that. It doesn't seem to matter that much, though, at least for aggregate and batched signature verification.

**Comment by kchalkias** [comment]
Did we eventually include "asm" in our benchmarks?

**Comment by jonas-lj** [comment]
> Did we eventually include "asm" in our benchmarks?

I did do some benchmarks with the "asm" feature, but it didn't seem to matter that much. But I'll make sure to include it in the benchmarks.

**Comment by huitseeker** [comment]
@kchalkias yes https://github.com/MystenLabs/fastcrypto/commit/6c78d8642b93d7b23c353cef34a30de3dd9faa97

**Comment by jonas-lj** [comment]
There are benchmarks for all functions in the criterion report, so I think it's ok to close this issue now. Otherwise let me know.
