### ISSUE TITLE
Update fastcrypto's readme with selected benchmark diagrams

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#150]
This will allow showcase our results easier (was recently asked to share our data from many different orgs and firms)

**Comment by jonas-lj** [comment]
There's a PR ready now. It links to the report and shows the diagram for batched verification. I think adding too many diagrams to the readme will be cluttered, but we could add a table also. What do you think @kchalkias ?

**Comment by kchalkias** [comment]
Yes just a dated sample (1 table and 1 diagram) and point them to the actual criterion bench page
