### ISSUE TITLE
Keypair Serde is Broken

### ISSUE THREAD

**Issue by punwai** [MystenLabs/fastcrypto#18]
### Description
Keypair serializes, but does not deserialize when trying to test it out in MystenLabs/narwhal#557. Does not break Narwhal nor Sui so continuing with MystenLabs/narwhal#557 anyways.

To replicate this issue, run the following test:
```
#[test]
fn test_kp_serde() {
    let kp = keys().pop().unwrap();
    let serialized = bincode::serialize(&kp).unwrap();
    let deserialized: Ed25519KeyPair = bincode::deserialize(&serialized).unwrap();
}
```
We get this error:
```
thread 'bls12377_tests::test_kp_serde' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid Base64 encoding")', crypto/src/tests/bls12377_tests.rs:375:75
```

Upon further digging, it looks like removing this line fixes the issue:
```
#[serde(tag = "type")] // REMOVE THIS LINE
pub struct Ed25519KeyPair {
    name: Ed25519PublicKey,
    secret: Ed25519PrivateKey,
}
```

**Comment by kchalkias** [comment]
@punwai has this been resolved?

**Comment by huitseeker** [comment]
I have an upcoming fix, I'll test its compatibility w/Sui before opening a PR though.
 https://github.com/huitseeker/fastcrypto/pull/new/test_keypair_serde
