### ISSUE TITLE
[TB-crypto] Define a crypto-standard for Timestamped Benchmarks

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#181]
As our backends evolve, we might realize that down the road the efficiency of some schemes might be updated, perhaps also have additional parallelization improvements etc. Let's maintain a timestamped bench-results page with diagrams to track improvement. **Then protocol designers (and crypto paper authors) can really have a fair (and evolving) primitive comparison matrixes**. 

TL;DR We receive incredibly positive feedback that fastcrypto gradually starts being a de facto reference implementation for future research papers and protocol designers due to providing a well-defined comparison matrix between some of the fastest implementations in the space + for batch/aggregated (in the future w precomputed table) + parallelization-friendly versions etc. Our results already:

- changed the perception on how modern BLS impl. perform compared to the fastest ECDSA and EdDSA crates.
- identified unfair or outdated comparisons reported by some lib authors.
- some implementations perform extra serialization operations and/or others provide different security guarantees. for instance:
    -- BLS fast_aggregation_verify can be applied when rogue key attack protection already took place (ie via PoP sigs)
    -- another case in ed25519 batch-verify where two different libs use as inputs Objects Vs raw bytes (and thus extra serialization steps are required in the 2nd, skewing the comparison results a bit).
    -- another case is base64 malleable vs non-malleable and/or constant vs variable time implementations.
- how can someone combine different backends for different setups and input sizes (ie see the results for base64 encoders where for different input sizes we have another winner impl).
- what are the sweet points when we compare the two fastest Rust implementations (or ports). Example: Many ask about "When aggregated BLS starts winning against batched ed25519?", "what if we used a parallelized version?" etc. 
- we already have evidence that some cryptographic protocols, which were supposed to be hanging behind re performance, are in practice a lot faster than expected and vice versa.
- how parallel and/or vectorized implementations perform against each other (ie AVX2, no-threads BLST etc)?
- easily compare against optimized and experimental versions (i.e., with precomputed tables, removing one half-scalar in random combinations, half-aggregation etc).

**Comment by jonas-lj** [comment]
I suggest we do this by adding continuous benchmarking in the CI. The benchmarks could eg. be done on 'publish'. There are tools to do this and generate diagrams: https://github.com/marketplace/actions/continuous-benchmark. I'll test one out on a fork to see if it works.

**Comment by jonas-lj** [comment]
> I suggest we do this by adding continuous benchmarking in the CI. The benchmarks could eg. be done on 'publish'. There are tools to do this and generate diagrams: https://github.com/marketplace/actions/continuous-benchmark. I'll test one out on a fork to see if it works.

It's an open question [if we can get reliable results using a VM in the cloud ](https://bheisler.github.io/post/benchmarking-in-the-cloud/), but there are at least two different options for outputs:
* [Output generated by criterion](https://jonas-lj.github.io/bench_test/reports/)
* [Output generated by continuous-benchmark](https://jonas-lj.github.io/bench_test/dev/bench/)
Both can also be run locally, if we decide that doing it in the cloud gives to much variance in the results.

**Comment by jonas-lj** [comment]
The benchmarks are now online at https://mystenlabs.github.io/fastcrypto/benchmarks/criterion/reports/ and will be run again on every release.
