### ISSUE TITLE
[ECDSA] add benchmarks for ecrecover vs sig verify

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#185]
Needed for Sui's ECDSA secp256k1 account key support + lets provide a justified answer to [Lúcás](https://twitter.com/cronokirby): [see tweet](https://twitter.com/cronokirby/status/1586098778951630848?s=20&t=h3Gwq5aYnUux3gJBBtdQTg)

**Comment by jonas-lj** [comment]
I've done the benchmarks now, and the difference is only about 10-12%.

![Verify vs ecrecover](https://user-images.githubusercontent.com/6288307/207005279-479db227-3ed9-4c0a-9f5c-740cb34f4ebc.png)

**Comment by jonas-lj** [comment]
I've posted an answer to Lucas tweet with the results https://twitter.com/lindstrom_dk/status/1602231037735702529.

**Comment by jonas-lj** [comment]
Note that since the ECDSA schemes in fastcrypto currently only support verification by public key recovery, the benchmarks were done manually by changing the code. When #292 is merged, we can add benchmarks to the benchmark suite.
