### ISSUE TITLE
[crypto] Ad-hoc deserialization from ssh-keygen armored files

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/fastcrypto#19]
For genesis, we have node runners that like to generate their keypair (EdDSA) from the [`ssh-keygen`](https://www.man7.org/linux/man-pages/man1/ssh-keygen.1.html) tool (a well-trusted implementation).

We would like to be able to import and deserialize an EdDSA keypair as generated from ssk-keygen, which means interpreting the armored format for the private key. We would add this functionality as a simple pub function in out `ed25519.rs`, which would be integrated in our tooling Sui-side.

The rust crate [`rust-sshkeys`](https://github.com/dnaeon/rust-sshkeys) provides a lot of tooling for reading the ssh pem files, but unfortunately, at the moment, only reads Pubkeys (whereas we would like to generate a keypair, hence reading private keys).

**Comment by kchalkias** [comment]
cc: @huitseeker and @joyqvq is this still an active issue?

**Comment by joyqvq** [comment]
this is still useful. let me revisit this next week.

**Comment by joyqvq** [comment]
https://github.com/MystenLabs/base64pemkey
