### ISSUE TITLE
[crypto] Make sure the crypto API does not expose the hash of a message

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/fastcrypto#20]
At the moment signature verification passes a hash as an argument:
https://github.com/MystenLabs/narwhal/blob/36968d41de1680a8d79dbc3f7c301f322ba4ad1c/crypto/src/lib.rs#L210-L230

https://github.com/SalusaSecondus/CryptoGotchas/blob/master/README.md#signatures
> An attacker mustn't be allowed to select the actual value being validated in the signature. (The hashing step in all standard signatures defends against that as they can only select the hash pre-image, not the value of the hash.) If they could then they could trivially craft a valid signature for an arbitrary public key by (essentially) generating a random signature and seeing what message would be verified by that signature and then returning that message/signature pair.

**Comment by benr-ml** [comment]
The current code & APIs correctly verify signatures using messages
