### ISSUE TITLE
Ensure that private keys are zeroized in BLS12377

### ISSUE THREAD

**Issue by jonas-lj** [MystenLabs/fastcrypto#208]
The test_sk_zeroization_on_drop test did not verify that the bytes of the private key in the celo_bls::PrivateKey field in BLS12377 is zeroized, but only that it's no longer equal to the private key. But they should have been zeroized and the test should reflect that.

See also #206

**Comment by kchalkias** [comment]
resolved in https://github.com/MystenLabs/fastcrypto/pull/206
