### ISSUE TITLE
Problem building SUI repo with local changes to fastcrypto

### ISSUE THREAD

**Issue by arthurgreef** [MystenLabs/fastcrypto#220]
Hi I'm trying to build the sui repo with a change in the Cargo.toml file 
```fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "bbb2d02a7a64c27314721748cc4d015b00490dbe" }
fastcrypto = { path = "../fastcrypto/fastcrypto"}
```
So that I can reference  a local repo o ffastcrypto reset to the revision
```
git reset --hard bbb2d02a7a64c27314721748cc4d015b00490dbe
```
I get the following error. Any ideas on what I am doing wrong? Thanks.
```error[E0277]: the trait bound fastcrypto::bls12381::min_sig::BLS12381PublicKey: MallocSizeOf` is not satisfied
   --> narwhal/types/src/primary.rs:148:48
    |
148 | #[derive(Builder, Clone, Default, Deserialize, MallocSizeOf, Serialize)]
    |                                                ^^^^^^^^^^^^ the trait `MallocSizeOf` is not implemented for `fastcrypto::bls12381::min_sig::BLS12381PublicKey```

**Comment by jonas-lj** [comment]
This happens because `MallocSizeOf` is implemented for various structs from the fastcrypto repo in the [mysten-util-mem crate](https://github.com/MystenLabs/mysten-infra/tree/main/crates/mysten-util-mem), and Sui depends on these. 

So in order for your local setup to run, you also need to use a local version of mysten-util-mem in Sui, which should use the _exact_ same fastcrypto dependency as Sui. Currently, Sui has two sub crates depending on mysten-util-mem, namely narwhal/consensus and narwhal/types, so the dependencies Cargo-files in these crates should point to your local mysten-util-mem.

**Comment by arthurgreef** [comment]
Hi - I got past the `MallocSizeOf` problem but now I have a new problem even though I changed my sui `Cargo.toml` so that my ```mysten-network``` path to reference my local repo.

```rust
error[E0277]: the trait bound `OsRng: AllowedRng` is not satisfied
   --> narwhal/network/src/p2p.rs:66:50
    |
66  |                 crypto::NetworkKeyPair::generate(&mut rand::rngs::OsRng)
    |                 -------------------------------- ^^^^^^^^^^^^^^^^^^^^^^ the trait `AllowedRng` is not implemented for `OsRng`
    |                 |
    |                 required by a bound introduced by this call
    |
    = help: the following other types implement trait `AllowedRng`:
              StdRng
              ThreadRng
note: required by a bound in `narwhal_crypto::traits::KeyPair::generate`
   --> /mnt/wsl/PHYSICALDRIVE1p1/hashblock/fastcrypto/fastcrypto/src/traits.rs:221:20
    |
221 |     fn generate<R: AllowedRng>(rng: &mut R) -> Self;
    |                    ^^^^^^^^^^ required by this bound in `narwhal_crypto::traits::KeyPair::generate`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `narwhal-network` due to previous error
```

**Comment by jonas-lj** [comment]
That will require quite a few changes to Sui, so the easiest solution will probably be to use the most recent of Sui (or anything after 05d2fadcf473630b3a5b79d819e6b5af8ea1682c). That should actually also solve the `MallocSizeOf` problem.

**Comment by arthurgreef** [comment]
Hi I pulled the latest sui and fastcrypto repos. I then made the following changes to get sui to use my local fastcrypto repo.

Changed:
```rust
#fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "b6411e014255c9e2a0f6dff00478bc45d76e9f5d" }
```
to
```
fastcrypto = { git = "file:///mnt/wsl/PHYSICALDRIVE1p1/hashblock/fastcrypto", rev = "b6411e014255c9e2a0f6dff00478bc45d76e9f5d" }
```
everywhere.

I now get the following error. Any ideas? Thanks.

```rust
error: failed to get `fastcrypto` as a dependency of package `workspace-hack v0.1.0 (/mnt/wsl/PHYSICALDRIVE1p1/hashblock/sui/crates/workspace-hack)`

Caused by:
  failed to load source for dependency `fastcrypto`

Caused by:
  Unable to update file:///mnt/wsl/PHYSICALDRIVE1p1/hashblock/fastcrypto?rev=b6411e014255c9e2a0f6dff00478bc45d76e9f5d

Caused by:
  revspec 'b6411e014255c9e2a0f6dff00478bc45d76e9f5d' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by arthurgreef** [comment]
Fixed by replacing this:
```
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "b6411e014255c9e2a0f6dff00478bc45d76e9f5d" }
```
with this:
```
fastcrypto = { path = "../fastcrypto/fastcrypto" }
```
Thanks.
