### ISSUE TITLE
Ensure all of our benchmarks are single threaded

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#221]
This is to provide fairness

**Comment by jonas-lj** [comment]
The blst crate has a _no-threads_ feature we can enable, and celo has a set of features set to enable it, which we have put together collective _threads-bls_12_377_ feature and enable by default. So running with `--no-default-features and --features no-threads-blst` will force these two crates to be single threaded. For reference, I include a plot comparing benchmarks with single-threaded vs multi-threaded for batched verification on the same message.

![single-multi](https://user-images.githubusercontent.com/6288307/200800862-2199ec18-dedc-468b-802e-785122ae6bb9.png)

It seems like the rust_secp256k1 and ed25519-consensus crates don't have similar features, so we cannot disable threads for these crates using features. I'll profile the benchmarks with these to see, if they even use multiple threads.

**Comment by jonas-lj** [comment]
I've done some profiling now using Xcode instruments. The blst crate with the no-threads feature enabled, secp256k1 and ed25519 does indeed only use a single thread. BLS12377, however, uses multiple threads even without the parallel feature set. I'll investigate options as to how (or if) this can be configured.

![Screenshot 2022-11-09 at 14 10 23](https://user-images.githubusercontent.com/6288307/200839046-40e1c46a-b7a9-4119-9c27-9ac807520fbc.png)

To reproduce, use the command `cargo instruments -t "Time Profiler" --bench crypto --no-default-features --features "no-threads-blst"` and commented out all but a single test on each run.

**Comment by jonas-lj** [comment]
After a hint from @huitseeker, I found the issue. It turned out to be because the ark crates were imported both in fastcrypto _and_ fastcrypto-zkp, and in the latter with the parallel feature set. So we can fix this by running the benchmarks from the fasstcrypto/fastcrypto crate. I'll submit a pr fixing this.

**Comment by jonas-lj** [comment]
For reference, I include the above plots where BLS12377 are indeed running single threaded. Surprisingly enough, for batch verification, single threaded seems to be a bit faster and with a lot less variance in the timings.
![Unknown](https://user-images.githubusercontent.com/6288307/201304149-776d0d3f-3562-4482-bb66-247b7942c9b5.png)
