### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by jonas-lj** [MystenLabs/fastcrypto#244]
The error types in FastCryptoError does not currently give a lot of information about what caused them, and while this opaqueness is to some degree intended, we should add a bit more clarity to them. This could be done either by adding more error types or by adding messages to the errors or a combination.

@kchalkias review of #243 gives a few suggestions on what we should change.

**Comment by benr-ml** [comment]
+1 for error messages.

Different error types are needed when we believe that the caller would use them differently, but I doubt that anyone would handle differently errors like InvalidInputs vs InputTooShort. General error types like InvalidInputs, OsResourceError, etc should suffice.

Adding an optional error string to errors makes sense for logging purposes.

**Comment by benr-ml** [comment]
Closed in #410
