### ISSUE TITLE
Implement MSKR for min_sig as well

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#271]
Actually this should be the default mode, as our benchmarks say this is faster + sigs are reused, while pks are usually static for BFT committees (at least per epoch).

**Comment by asonnino** [comment]
I already did it for the MSKR benchmarks, I can merge it from he `mskr-bench` branch

**Comment by asonnino** [comment]
Although it contains a bit of code duplicate that could be avoided through a clever macro
