### ISSUE TITLE
[serialization] BLS12381AggregateSignature does not round-trip

### ISSUE THREAD

**Issue by bmwill** [MystenLabs/fastcrypto#338]
BLS12381AggregateSignature does not round-trip serialization:

```
let sig = BLS12381AggregateSignature::default();
let bytes = bcs::to_bytes(&sig).unwrap();
bcs::from_bytes(&bytes).unwrap_err();
```

Edit:

I actually think the issues ends up being the serialize/deserialize impls here: https://github.com/MystenLabs/sui/blob/main/crates/sui-types/src/sui_serde.rs#L219-L243

**Comment by bmwill** [comment]
It seems removing the `#[serde_as(as = "AggrAuthSignature")]` annotation on this struct fixes the issue:

```
#[serde_as]
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct AuthorityQuorumSignInfo<const STRONG_THRESHOLD: bool> {
    pub epoch: EpochId,
    #[schemars(with = "Base64")]
    #[serde_as(as = "AggrAuthSignature")]
    pub signature: AggregateAuthoritySignature,
    #[schemars(with = "Base64")]
    #[serde_as(as = "SuiBitmap")]
    pub signers_map: RoaringBitmap,
}
```

**Comment by benr-ml** [comment]
It is currently working as intended, I believe it's because of the recent changes we did with the serialization of `BLS12381AggregateSignature`.
In any case, `AggrAuthSignature` is removed in https://github.com/MystenLabs/sui/pull/8340.
