### ISSUE TITLE
Implement Wesolowski VDF

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#343]
Note that we don't need to handle the trusted setup part at this stage.
Paper: https://eprint.iacr.org/2018/623
Analysis and comparison with Pietrzak scheme: https://crypto.stanford.edu/~dabo/pubs/papers/VDFsurvey.pdf

**Comment by jonas-lj** [comment]
Just to clarify: We do as Ethereum 2.0 and use Wesolowski + RSA groups, and we can assume that an RSA group with unknown factorization is given?

I'll start by adding RSA groups to fastcrypto and then build the VDF afterwards.

**Comment by kchalkias** [comment]
@jonas-lj exactly, we assume that each application can pick their own group (Sui doesn't need to know how this was computed, ie different smart contracts might pin different `n`)

**Comment by jonas-lj** [comment]
> @jonas-lj exactly, we assume that each application can pick their own group (Sui doesn't need to know how this was computed, ie different smart contracts might pin different `n`)

That makes sense. I think we could make the construction for generic hidden order groups, allowing eg. ideal class groups in the future such that no trusted setup is needed at all.
