### ISSUE TITLE
[serialization] BLS12381AggregateSignature should not have an option<signature>

### ISSUE THREAD

**Issue by benr-ml** [MystenLabs/fastcrypto#345]
It results in a non standard serialized representation, which is actually returned also to users via APIs.

Alternatives:
- use inf as the default/empty signature
- do not implement `Default` and remove `Option<sig>`. Instead, modify NW's structs to use `Option<BLS12381AggregateSignature>`.

**Comment by kchalkias** [comment]
fixed
