### ISSUE TITLE
Helper fun to convert ECDSA recoverable to non recoverable and vice versa

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#360]
This has been requested multiple times, especially from non-recoverable to recoverable, ie iPhone enclaves are only outputting non-recoverable.
any of @joyqvq and @jonas-lj who are familiar with that repo part.

**Comment by jonas-lj** [comment]
Recoverable to non-recoverable is already part of #292, but I'll make sure to add the non-recoverable to recoverable also.

**Comment by jonas-lj** [comment]
Won't the easiest way to do this be to try the different possibilities for recovery id and then compare with a public key or an address? This is at least the way it's done in https://www.secg.org/sec1-v2.pdf sec 4.1.6.

Also, I'll add this in another PR. The PR of #292 is large enough as it is...

**Comment by joyqvq** [comment]
agreed, trying all 4 (but more like 3) recovery id should work
