### ISSUE TITLE
Rename to zip215 vs ed25519?

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#47]
Wondering if we should avoid mentioning ed25519 directly and switch to zip215 for clarity. Obviously we should explain that it's an ed25519 mode.

**Comment by joyqvq** [comment]
I concern that when external users searches for Ed25519 in our codebase, it is hard to tell what zip215 is. IMO zip215 is the standard for verification, not for other representation of the eddsa key. Perhaps renaming the verify method to verify_with_zip215 is more appropriate?

**Comment by kchalkias** [comment]
@joyqvq let's check how zcash is handling this and definitely ensure we have clear comments in docs and comments.

**Comment by kchalkias** [comment]
cc: @benr-ml who might have similar experience and ideas.

**Comment by benr-ml** [comment]
I think that documenting this is enough - ZIP215 is just a set of additional verification criteria that all honestly generated signatures should satisfy.

**Comment by kchalkias** [comment]
Great, makes sense: we should do exactly what zCash promotes in their zebra lib and docs and it seems they also refer it as ed25519 with zip215 validation https://github.com/ZcashFoundation/ed25519-zebra
