### ISSUE TITLE
Batch verification could use smaller scalars (both in ed25519 and BLS)

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#492]
Atm we use 128bits scalars for randomizing EC points during batch verification. As @benr-ml and Vitalik mentioned (see: https://ethresear.ch/t/fast-verification-of-multiple-bls-signatures/5407 (last paragraph) we could in theory relax it to [0, 2^64) or [0, 2^96) as this is an online attack + we have the extra BFT guarantee, where someone should apply this attack to more than f+1 honest validators to break system's security.
The worst case scenario is one of the validators forks, but again this is a speculative attack due to its online (cannot be applied offline) nature. Maybe we could tolerate it.

This applies to both ed25519 (user batch ver) and BLS (validator sig ver)

**Comment by benr-ml** [comment]
Resolved in https://github.com/MystenLabs/sui/pull/9192#pullrequestreview-1336388374
