### ISSUE TITLE
Add RSA signature verification support

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#524]
There are many dapps that might need to parse and verify an RSA signature from some web2 service.
As there are many modes, let's originally support RS256 as defined in the JWT standard, which is probably the most common version of RSA as it signs the sha256 of a message.

A good candidate is the `rsa` crate, it's also used by the rust-jwt-simple crate as well
https://github.com/jedisct1/rust-jwt-simple/blob/master/Cargo.toml#L28

**Comment by jonas-lj** [comment]
@kchalkias Do we need this for other usages than parsing and verifying jwt's? Because if not, we might just use the rust-jwt-simple crate directly.
