### ISSUE TITLE
Unsafe Fast Hash support

### ISSUE THREAD

**Issue by kchalkias** [MystenLabs/fastcrypto#74]
This will be required for benchmarking (similarly to empty/dummy signatures). It cannot empty (as collisions can break operations), maybe we can use the fastest non-cryptographically secure hash function for this purpose.

**Comment by jonas-lj** [comment]
Based on a bit of desktop research, the fastest such non cryptographic hash function seems to be [xxHash3](https://cyan4973.github.io/xxHash/). This is based on the benchmarks they provide on their website and this [discussion](https://news.ycombinator.com/item?id=10667328). If no-one objects, I'll give xxHash a go and do some basic benchmarks to verify.
